In [1]:
#Example with python list
h=[1.71,1.58,1.67,1.89,1.73]
w=[67.9,78.8,56.8,49.3,73.2]
BMI=w/h**2
print(BMI)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [2]:
#Example with numpy array
h=[1.71,1.58,1.67,1.89,1.73]
w=[67.9,78.8,56.8,49.3,73.2]
import numpy as np
nh=np.array(h)
nw=np.array(w)
BMI=nw/nh**2
print(BMI)


[23.22082008 31.56545425 20.36645272 13.80140534 24.45788366]


### Speed check of numpy and python list

In [3]:
#Example with Python lists
l=range(1000)
%timeit [i**2 for i in l]

937 µs ± 19.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
#Example with numpy 
import numpy as np
a=np.arange(1000)
%timeit a**2

4.23 µs ± 191 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### creation of arrays

In [5]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
#to know dimensions
a.ndim

1

In [8]:
#to know number of rows and columns
a.shape

(6,)

In [9]:
#to know the length
len(a)

6

In [10]:
#2D,3D,4D...
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
b.ndim


2

In [12]:
b.shape

(2, 3)

In [17]:
b=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[4,5,6],[7,8,9]],[[10,11,12],[4,5,6],[7,8,9]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [ 4  5  6]
  [ 7  8  9]]]


In [18]:
b.ndim


3

In [19]:
#line space 
a=np.linespace(0,1,6)
print(a)

AttributeError: module 'numpy' has no attribute 'linespace'

In [20]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
c=np.zeros((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#diagonal array
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [24]:
np.diag(a)

array([1, 2, 3])

In [25]:
#Create array using random
a=np.random.rand(4)
print(a)

[0.1451037  0.16917642 0.39445733 0.49006898]


In [26]:
b=np.random.randn(4)
print(b)

[ 1.11115266  0.07560458 -0.53062826  1.34067894]


In [1]:
import numpy as np
r=np.random.randint(20,36,4)
print(r)

[24 23 22 34]


# Basic Data Types:

In [2]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
a.dtype

dtype('int32')

In [4]:
b=np.arange(10,dtype='float64')
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [5]:
z=np.zeros(4)
print(z)

[0. 0. 0. 0.]


In [6]:
x=np.ones(4)
print(x)

[1. 1. 1. 1.]


In [7]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
y=np.eye(3)
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
d=np.array([10.5+5j,20+6j])
print(d)

d.dtype

[10.+5.j 20.+6.j]


dtype('complex128')

In [10]:
#boolian data type
b=np.array([True,False,False,True])
print(b)
b.dtype

[ True False False  True]


dtype('bool')

In [11]:
#string type
s=np.array(["Akhila","Venky","Hello"])
s.dtype

dtype('<U6')

# Indexing & Slicing

## Indexing:

In [12]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(a[4])

4


In [14]:
#indexing in 2D array
b=np.diag([1,2,3,4])
print(b)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [15]:
print(b[2,2])

3


In [16]:
print(b[3,3])

4


In [17]:
b[3,2]=20
print(b)

[[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  3  0]
 [ 0  0 20  4]]


## slicing

In [18]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
#Using slicing
print(a[2:6])

[2 3 4 5]


In [20]:
print(a[0:10:2])

[0 2 4 6 8]


In [21]:
a[5:]=10
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


In [22]:
a[1]=20
print(a)

[ 0 20  2  3  4 10 10 10 10 10]


In [23]:
a[3:5]=99
print(a)

[ 0 20  2 99 99 10 10 10 10 10]


In [24]:
a=np.arange(10)
b=np.arange(5)
a[5:]=b[::-1]
print(a)


[0 1 2 3 4 4 3 2 1 0]


In [25]:
b=np.arange(10)
print(b[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [27]:
print(b[5::-1])
print(b)

[5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]
